services:
  main-service:
    build: .
    networks:
      - kafka-network
      - app-network
    env_file:
      - .env
    environment:
      - KAFKA_BROKER=kafka:9092
      - POSTGRES_DOCKER_URL=postgres://postres:5431/postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata: