server:
  port:
    8082


token:
  key: ${JWT_KEY}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
    name: ${POSTGRES_DB}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
